#!/bin/bash

# Program Startup

pgrep -x sxhkd > /dev/null || sxhkd &

picom --config $HOME/.config/picom/picom.conf &

setxkbmap -option grp:alt_shift_toggle es,us &
xsetroot -cursor_name left_ptr &

$HOME/.local/bin/wal -i $HOME/images/wallpapers/current.png &
. "${HOME}/.cache/wal/colors.sh"

$HOME/.config/polybar/launch.sh

# BSPWM configs
bspc monitor -d 1 2 3 4

bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"

bspc config border_width         4
bspc config window_gap          14

bspc config focus_follows_pointer true
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Layout and program rules
bspc rule -a mpv state=floating
bspc rule -a spotify desktop='^4'

bsp-layout set wide 4 -- --master-size 0.7

